{% set version = "4.0.0.0" %}
{% set name = "planarity" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/graph-algorithms/edge-addition-planarity-suite/releases/download/Version_{{ version }}/planarity-{{ version }}.tar.gz
  sha256: df3c86c32fd37b801079aea7de67675efdef12ada557cbcaae821e81b8db438d
  patches:   # [win]
    - 0001-Adapt-for-Windows-build.patch  # [win]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('planarity', max_pin='x.x.x') }}

requirements:
  build:
    - libtool      # [unix]
    - automake     # [unix]
    - autoconf     # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake        # [win]
    - make         # [unix]
  host:

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h   # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}.a               # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib           # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so              # [linux]
    - if not exist %LIBRARY_LIB%/{{ name }}.lib exit 1    # [win]
    - if not exist %LIBRARY_INC%/{{ name }}/{{ name }}.h exit 1    # [win]
    - planarity -h | exit 0

about:
  home: https://github.com/graph-algorithms/edge-addition-planarity-suite
  license: BSD-3-Clause
  license_file: LICENSE.TXT
  summary: |
    This code project provides a library for implementing graph algorithms as well
    as implementations of several planarity-related graph algorithms
  dev_url: https://github.com/graph-algorithms/edge-addition-planarity-suite

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
