travis:
  secure:
    BINSTAR_TOKEN: Rq0aFM6gqiGsFR9LjjvtBiNBfXwaHp78o4gVTGY6jUJdJ91DYEzu/IvWLlMOKJaU/lg68EDSBxkuUDld8+KiSHY5EMhxatYRFrcBC7ITYt488Q1AYgAwvtrOe9y4lsLhs5/oeDV2BuP3N1a3Tg2cMnrt1V9uiZ+N9uf9mWHUk8ahcq9HbiS96NBaXOcT04SNKf5U63+NsZIU29IvKP3f2vBJPA/qxnlmEvBzGcKEqapsnu7L/6bxdjDwoHVDhTJuYn1HZGnokKJWegtliJRXg9k6UMPunezNYhBT7ZkO6StDlIz3btXfENuqcYABHPiJyJ2gE3qmusOOakdFNRfEcQ58MooC1yP4FR5QqZByD68lKDG1yh7Ny/+YgDtcAVEdW8B0iNfpkAGJ7/8pE3x4qyuRSRyvwovrGDF0feNlVY7oVVcsIic+4U3aitlUhJxjFDDk918IQsQDznjn9OULUHYgUXtLg5nfv10ZOMV4mkZAHvLU72jSBhZ8kgxuZ3yXO7J9I25ZmltDhovdz+pFq7JC6hmL6z28KXMx4TIogcI3YJTUZt9MkIZE6wnHwadIwSH7KR7C95BcDr9NvECv+xlJkzvWgdPhG89fPpu4XEGE+MUwUNEBTj3o+6afssmXPn+QepqPYroBE7edP6pRhWU7fW3v+gtMNeAbpOUIeLo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
