appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: PKrhhB46tbk7zYNsbaxoo4ecHWL5ugaXa+oKUv70MJbjgRNQkXVirLiQ7oXK7towge8U2cwgADayarp01SMtmSC0bfL2CUivKbEpqy7Vbw2c27dUQViRsF3T1i++lD0guAsIHHvK23XSYmZmjv2qNeoQsq9ROnIKOAmM9Ds3KId0YAeLvmAK9/QtejT2LW3+chwGhI+oyhCB4nPvV21iAOLhExvM9Rla2p/GCQnjRp/PRO8WqEUh2UV1ToWGCNa+sOQGT1c63M9gGiwRo1a7AY8Ur6gbcLdixWsJ7jP0jEksQvUmZektpkhyx/QBbHrm3+1w/Xh2rd+EvkqLV2/cFDLXyQSIKT+8UwZ05eHH43nuw5T0l0supPZMraZo+M8utwPbu4HhPtoUaolb8JCccWUVH+OZTT2sfsCmJA0nOXHaVIhTVCblP58Udn8pbWcgV+2Qpo+t1TUxrJ4CO2V8uLvuRIvna4cni0Lp8Mw9Bj9GIlA49EuOmAd/f69fkMPFd+uled8c1maxHGIsMeQxoVyHcU3Io6W12JKiCKlNy65Z4upfL8OSqvUmVxOxTn1JdKSOigubJUpUKcuwnCKt0zuNFCFYb6uZlheVXt6GB2Detk3sKaEizmNNfZL3DZm8CgumwVHZ8LObCTC7W7EnP08T+1N7LRwROZdDR5C8eE8=}
